///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;
using System.Diagnostics;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace trial
{
    public partial class firefox
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Key_Sequence_SearchBox()
        {
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex1' with focus on 'Dubber.SearchBox'.", repo.Dubber.SearchBoxInfo);
            repo.Dubber.SearchBox.PressKeys("ranorex1");
           //// repo.Dubber.SearchBox.PressKeys("enter");
        }

        public void Mouse_Click_DropDownLogout()
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.DropDownLogout' at Center.", repo.Dubber.DropDownLogoutInfo);
            repo.Dubber.DropDownLogout.Click();
           string path = @"C:\Users\Sandeep\Downloads\fsdf-Callflow.xml";
           File.Delete(path);
        }

      
    }
}