///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace trial
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the newrepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("f69058ce-4ad1-4559-b10f-18987b6c48b1")]
    public partial class newrepo : RepoGenBaseFolder
    {
        static newrepo instance = new newrepo();
        newrepoFolders.DubberMozillaFirefoxAppFolder _dubbermozillafirefox;
        newrepoFolders.DubberAppFolder _dubber;

        /// <summary>
        /// Gets the singleton class instance representing the newrepo element repository.
        /// </summary>
        [RepositoryFolder("f69058ce-4ad1-4559-b10f-18987b6c48b1")]
        public static newrepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public newrepo() 
            : base("newrepo", "/", null, 0, false, "f69058ce-4ad1-4559-b10f-18987b6c48b1", ".\\RepositoryImages\\newrepof69058ce.rximgres")
        {
            _dubbermozillafirefox = new newrepoFolders.DubberMozillaFirefoxAppFolder(this);
            _dubber = new newrepoFolders.DubberAppFolder(this);
        }

#region Variables

        string _varnew = "";

        /// <summary>
        /// Gets or sets the value of variable varnew.
        /// </summary>
        [TestVariable("1b3d8bbd-e4f5-4045-8bae-23656b26a0cb")]
        public string varnew
        {
            get { return _varnew; }
            set { _varnew = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f69058ce-4ad1-4559-b10f-18987b6c48b1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The DubberMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("ff697b5d-960d-4fb4-9d8d-33deb0566dae")]
        public virtual newrepoFolders.DubberMozillaFirefoxAppFolder DubberMozillaFirefox
        {
            get { return _dubbermozillafirefox; }
        }

        /// <summary>
        /// The Dubber folder.
        /// </summary>
        [RepositoryFolder("4c030854-374f-486a-971b-bcb282aa331e")]
        public virtual newrepoFolders.DubberAppFolder Dubber
        {
            get { return _dubber; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class newrepoFolders
    {
        /// <summary>
        /// The DubberMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("ff697b5d-960d-4fb4-9d8d-33deb0566dae")]
        public partial class DubberMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            newrepoFolders.GroupingFolder _grouping;

            /// <summary>
            /// Creates a new DubberMozillaFirefox  folder.
            /// </summary>
            public DubberMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DubberMozillaFirefox", "/form[@title='Dubber - Mozilla Firefox']", parentFolder, 30000, null, true, "ff697b5d-960d-4fb4-9d8d-33deb0566dae", "")
            {
                _grouping = new newrepoFolders.GroupingFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ff697b5d-960d-4fb4-9d8d-33deb0566dae")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ff697b5d-960d-4fb4-9d8d-33deb0566dae")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Grouping folder.
            /// </summary>
            [RepositoryFolder("a1a01c2b-3e8b-4aa2-9ba1-64a8ee101914")]
            public virtual newrepoFolders.GroupingFolder Grouping
            {
                get { return _grouping; }
            }
        }

        /// <summary>
        /// The GroupingFolder folder.
        /// </summary>
        [RepositoryFolder("a1a01c2b-3e8b-4aa2-9ba1-64a8ee101914")]
        public partial class GroupingFolder : RepoGenBaseFolder
        {
            RepoItemInfo _emailaddressInfo;

            /// <summary>
            /// Creates a new Grouping  folder.
            /// </summary>
            public GroupingFolder(RepoGenBaseFolder parentFolder) :
                    base("Grouping", "container[@accessiblerole='Grouping']", parentFolder, 30000, null, false, "a1a01c2b-3e8b-4aa2-9ba1-64a8ee101914", "")
            {
                _emailaddressInfo = new RepoItemInfo(this, "EmailAddress", "container[@accessiblerole='PropertyPage']/?/?/container[@accessiblename='Dubber']/element[2]/element[2]/element[1]/element/element[2]/element[@accessiblerole='None']/element[@accessiblerole='None']/element[@accessiblerole='None']/element[1]/?/?/text[@accessiblename='Email Address']", 30000, null, "0a48e23d-7453-41d7-83c4-374590f14add");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a1a01c2b-3e8b-4aa2-9ba1-64a8ee101914")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a1a01c2b-3e8b-4aa2-9ba1-64a8ee101914")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EmailAddress item.
            /// </summary>
            [RepositoryItem("0a48e23d-7453-41d7-83c4-374590f14add")]
            public virtual Ranorex.Text EmailAddress
            {
                get
                {
                    return _emailaddressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EmailAddress item info.
            /// </summary>
            [RepositoryItemInfo("0a48e23d-7453-41d7-83c4-374590f14add")]
            public virtual RepoItemInfo EmailAddressInfo
            {
                get
                {
                    return _emailaddressInfo;
                }
            }
        }

        /// <summary>
        /// The DubberAppFolder folder.
        /// </summary>
        [RepositoryFolder("4c030854-374f-486a-971b-bcb282aa331e")]
        public partial class DubberAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _userpasswordInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "/dom[@domain='tigers.dubber.net']", parentFolder, 30000, null, false, "4c030854-374f-486a-971b-bcb282aa331e", "")
            {
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "89b187fa-a8f5-406e-bed0-f7024828cc6b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4c030854-374f-486a-971b-bcb282aa331e")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4c030854-374f-486a-971b-bcb282aa331e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("89b187fa-a8f5-406e-bed0-f7024828cc6b")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("89b187fa-a8f5-406e-bed0-f7024828cc6b")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}