///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace trial
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The traaaacc recording.
    /// </summary>
    [TestModule("97818126-d843-4492-aa17-8cc68fed91b3", ModuleType.Recording, 1)]
    public partial class traaaacc : ITestModule
    {
        /// <summary>
        /// Holds an instance of the trialRepository repository.
        /// </summary>
        public static trialRepository repo = trialRepository.Instance;

        static traaaacc instance = new traaaacc();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public traaaacc()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static traaaacc Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://tigers.dubber.net/login' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("https://tigers.dubber.net/login", "IE", "", false, false, false, false, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'qa+4@dubber.net' with focus on 'Dubber.UserEmail'.", repo.Dubber.UserEmailInfo, new RecordItemIndex(1));
            repo.Dubber.UserEmail.PressKeys("qa+4@dubber.net");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'P@ssword1' with focus on 'Dubber.UserPassword'.", repo.Dubber.UserPasswordInfo, new RecordItemIndex(2));
            repo.Dubber.UserPassword.PressKeys("P@ssword1");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.SubmitButton' at Center.", repo.Dubber.SubmitButtonInfo, new RecordItemIndex(3));
            repo.Dubber.SubmitButton.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex1' with focus on 'Dubber.SearchBox'.", repo.Dubber.SearchBoxInfo, new RecordItemIndex(4));
            repo.Dubber.SearchBox.PressKeys("ranorex1");
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Enter' Press.", new RecordItemIndex(5));
            Keyboard.Press(System.Windows.Forms.Keys.Return, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.CustomerAccountNameRanorex' at Center.", repo.Dubber.CustomerAccountNameRanorexInfo, new RecordItemIndex(6));
            repo.Dubber.CustomerAccountNameRanorex.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.AccountInboundTab' at Center.", repo.Dubber.AccountInboundTabInfo, new RecordItemIndex(7));
            repo.Dubber.AccountInboundTab.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.ProfileDdt' at Center.", repo.Dubber.ProfileDdtInfo, new RecordItemIndex(8));
            repo.Dubber.ProfileDdt.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dubber.DropDownLogout' at Center.", repo.Dubber.DropDownLogoutInfo, new RecordItemIndex(9));
            repo.Dubber.DropDownLogout.Click();
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'Dubber'.", repo.Dubber.SelfInfo, new RecordItemIndex(10));
            Host.Local.CloseApplication(repo.Dubber.Self, new Duration(0));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
