///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace trial
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the trialRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("f0dc129b-cc16-425c-9478-70f420c71644")]
    public partial class trialRepository : RepoGenBaseFolder
    {
        static trialRepository instance = new trialRepository();
        trialRepositoryFolders.DubberAppFolder _dubber;

        /// <summary>
        /// Gets the singleton class instance representing the trialRepository element repository.
        /// </summary>
        [RepositoryFolder("f0dc129b-cc16-425c-9478-70f420c71644")]
        public static trialRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public trialRepository() 
            : base("trialRepository", "/", null, 0, false, "f0dc129b-cc16-425c-9478-70f420c71644", ".\\RepositoryImages\\trialRepositoryf0dc129b.rximgres")
        {
            _dubber = new trialRepositoryFolders.DubberAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f0dc129b-cc16-425c-9478-70f420c71644")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Dubber folder.
        /// </summary>
        [RepositoryFolder("d2cb67d4-6954-4f21-83aa-7c4f6318070c")]
        public virtual trialRepositoryFolders.DubberAppFolder Dubber
        {
            get { return _dubber; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class trialRepositoryFolders
    {
        /// <summary>
        /// The DubberAppFolder folder.
        /// </summary>
        [RepositoryFolder("d2cb67d4-6954-4f21-83aa-7c4f6318070c")]
        public partial class DubberAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _useremailInfo;
            RepoItemInfo _userpasswordInfo;
            RepoItemInfo _submitbuttonInfo;
            RepoItemInfo _searchboxInfo;
            RepoItemInfo _customeraccountnameranorexInfo;
            RepoItemInfo _accountinboundtabInfo;
            RepoItemInfo _profileddtInfo;
            RepoItemInfo _dropdownlogoutInfo;

            /// <summary>
            /// Creates a new Dubber  folder.
            /// </summary>
            public DubberAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dubber", "/dom[@domain='tigers.dubber.net']", parentFolder, 30000, null, false, "d2cb67d4-6954-4f21-83aa-7c4f6318070c", "")
            {
                _useremailInfo = new RepoItemInfo(this, "UserEmail", ".//input[#'user_email']", 30000, null, "32a76f1e-bf03-414d-84a3-c6b3a97c4ac1");
                _userpasswordInfo = new RepoItemInfo(this, "UserPassword", ".//input[#'user_password']", 30000, null, "506b6326-a16b-437f-9d6d-4b6adedfec32");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", ".//input[#'submit_button']", 30000, null, "8ecc00c1-3e05-4a6b-a868-6add4b26ef58");
                _searchboxInfo = new RepoItemInfo(this, "SearchBox", ".//input[#'search_box']", 30000, null, "36d2cb0b-7d75-446a-b86d-0d3f105ade48");
                _customeraccountnameranorexInfo = new RepoItemInfo(this, "CustomerAccountNameRanorex", ".//a[#'customer_account_name_ranorex']", 30000, null, "bd93969c-42ba-417c-867b-af00ea530ab1");
                _accountinboundtabInfo = new RepoItemInfo(this, "AccountInboundTab", ".//a[#'account_inbound_tab']", 30000, null, "d09aa076-9eb3-4b66-aa86-631bcc8c76e0");
                _profileddtInfo = new RepoItemInfo(this, "ProfileDdt", ".//a[#'profile-ddt']", 30000, null, "70e02438-7300-48ea-9ca3-15a2ddd886ce");
                _dropdownlogoutInfo = new RepoItemInfo(this, "DropDownLogout", ".//a[#'drop_down_logout']", 30000, null, "15a50208-38e9-4847-87b2-147de7953e0c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d2cb67d4-6954-4f21-83aa-7c4f6318070c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d2cb67d4-6954-4f21-83aa-7c4f6318070c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserEmail item.
            /// </summary>
            [RepositoryItem("32a76f1e-bf03-414d-84a3-c6b3a97c4ac1")]
            public virtual Ranorex.InputTag UserEmail
            {
                get
                {
                    return _useremailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserEmail item info.
            /// </summary>
            [RepositoryItemInfo("32a76f1e-bf03-414d-84a3-c6b3a97c4ac1")]
            public virtual RepoItemInfo UserEmailInfo
            {
                get
                {
                    return _useremailInfo;
                }
            }

            /// <summary>
            /// The UserPassword item.
            /// </summary>
            [RepositoryItem("506b6326-a16b-437f-9d6d-4b6adedfec32")]
            public virtual Ranorex.InputTag UserPassword
            {
                get
                {
                    return _userpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserPassword item info.
            /// </summary>
            [RepositoryItemInfo("506b6326-a16b-437f-9d6d-4b6adedfec32")]
            public virtual RepoItemInfo UserPasswordInfo
            {
                get
                {
                    return _userpasswordInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("8ecc00c1-3e05-4a6b-a868-6add4b26ef58")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("8ecc00c1-3e05-4a6b-a868-6add4b26ef58")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The SearchBox item.
            /// </summary>
            [RepositoryItem("36d2cb0b-7d75-446a-b86d-0d3f105ade48")]
            public virtual Ranorex.InputTag SearchBox
            {
                get
                {
                    return _searchboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SearchBox item info.
            /// </summary>
            [RepositoryItemInfo("36d2cb0b-7d75-446a-b86d-0d3f105ade48")]
            public virtual RepoItemInfo SearchBoxInfo
            {
                get
                {
                    return _searchboxInfo;
                }
            }

            /// <summary>
            /// The CustomerAccountNameRanorex item.
            /// </summary>
            [RepositoryItem("bd93969c-42ba-417c-867b-af00ea530ab1")]
            public virtual Ranorex.ATag CustomerAccountNameRanorex
            {
                get
                {
                    return _customeraccountnameranorexInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CustomerAccountNameRanorex item info.
            /// </summary>
            [RepositoryItemInfo("bd93969c-42ba-417c-867b-af00ea530ab1")]
            public virtual RepoItemInfo CustomerAccountNameRanorexInfo
            {
                get
                {
                    return _customeraccountnameranorexInfo;
                }
            }

            /// <summary>
            /// The AccountInboundTab item.
            /// </summary>
            [RepositoryItem("d09aa076-9eb3-4b66-aa86-631bcc8c76e0")]
            public virtual Ranorex.ATag AccountInboundTab
            {
                get
                {
                    return _accountinboundtabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The AccountInboundTab item info.
            /// </summary>
            [RepositoryItemInfo("d09aa076-9eb3-4b66-aa86-631bcc8c76e0")]
            public virtual RepoItemInfo AccountInboundTabInfo
            {
                get
                {
                    return _accountinboundtabInfo;
                }
            }

            /// <summary>
            /// The ProfileDdt item.
            /// </summary>
            [RepositoryItem("70e02438-7300-48ea-9ca3-15a2ddd886ce")]
            public virtual Ranorex.ATag ProfileDdt
            {
                get
                {
                    return _profileddtInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ProfileDdt item info.
            /// </summary>
            [RepositoryItemInfo("70e02438-7300-48ea-9ca3-15a2ddd886ce")]
            public virtual RepoItemInfo ProfileDdtInfo
            {
                get
                {
                    return _profileddtInfo;
                }
            }

            /// <summary>
            /// The DropDownLogout item.
            /// </summary>
            [RepositoryItem("15a50208-38e9-4847-87b2-147de7953e0c")]
            public virtual Ranorex.ATag DropDownLogout
            {
                get
                {
                    return _dropdownlogoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DropDownLogout item info.
            /// </summary>
            [RepositoryItemInfo("15a50208-38e9-4847-87b2-147de7953e0c")]
            public virtual RepoItemInfo DropDownLogoutInfo
            {
                get
                {
                    return _dropdownlogoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}